# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: vs2017-win2016
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*
pr: none

variables:
  - group: signingSecrets
  - group: nugetKeys
  - name: githubConnectionName
    value: Petabridge
  - name: projectName
    value: Petabridge.Tracing.Zipkin
  - name: githubRepositoryName
    value: petabridge/Petabridge.Tracing.Zipkin

steps:
- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'All SignClientUser=$(signingUsername) SignClientSecret=$(signingPassword) nugetpublishurl=https://api.nuget.org/v3/index.json nugetkey=$(nugetKey)'

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
     bin\nuget\*.nupkg